kind: Service
apiVersion: v1
metadata:
  name: consul-assets-pipeline-2
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: default
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-consul-assets-service-2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-assets-service
  labels:
    app: consul-assets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-assets-service
  template:
    metadata:
      labels:
        app: consul-assets-service
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: consul-assets-service
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080